"""encrypted_algorithm

Revision ID: 65fda2fc1cfe
Revises: c7aabd1334cf
Create Date: 2026-04-24 07:30:43.034929

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '65fda2fc1cfe'
down_revision: str | Sequence[str] | None = 'c7aabd1334cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_algorithm', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('encrypted_algorithm')

    # ### end Alembic commands ###
