"""quantifications

Revision ID: c7aabd1334cf
Revises: d556e849b813
Create Date: 2026-04-23 20:16:06.080501

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c7aabd1334cf'
down_revision: str | Sequence[str] | None = 'd556e849b813'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quantifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('chebi_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sample_ref', sa.String(), nullable=True),
    sa.Column('abundance', sa.Float(), nullable=True),
    sa.Column('normalization_method', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quantifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quantifications_abundance'), ['abundance'], unique=False)
        batch_op.create_index(batch_op.f('ix_quantifications_chebi_id'), ['chebi_id'], unique=False)
        batch_op.create_index('ix_quantifications_chebi_sample', ['chebi_id', 'sample_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_quantifications_sample_ref'), ['sample_ref'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quantifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quantifications_sample_ref'))
        batch_op.drop_index('ix_quantifications_chebi_sample')
        batch_op.drop_index(batch_op.f('ix_quantifications_chebi_id'))
        batch_op.drop_index(batch_op.f('ix_quantifications_abundance'))

    op.drop_table('quantifications')
    # ### end Alembic commands ###
