"""initial schema

Revision ID: d556e849b813
Revises:
Create Date: 2026-04-23 19:35:13.668554

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd556e849b813'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.bulk_insert(users_table, [{'id': 1, 'name': 'system'}])
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('format_version', sa.String(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_by', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_content_sha256'), ['content_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_file_sha256'), ['file_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_uri'), ['uri'], unique=True)

    op.create_table('provenance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('software', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_refs', sa.JSON(), nullable=False),
    sa.Column('output_refs', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('acquisition_mode', sa.String(), nullable=True),
    sa.Column('spectrum_count', sa.Integer(), nullable=False),
    sa.Column('instrument_manufacturer', sa.String(), nullable=True),
    sa.Column('instrument_model', sa.String(), nullable=True),
    sa.Column('polarity', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_acquisition_mode'), ['acquisition_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_instrument_manufacturer'), ['instrument_manufacturer'], unique=False)

    op.create_table('studies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('isa_investigation_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studies_title'), ['title'], unique=False)

    op.create_table('identifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('chebi_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('spectrum_index', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identifications_chebi_id'), ['chebi_id'], unique=False)
        batch_op.create_index('ix_identifications_chebi_score', ['chebi_id', 'score'], unique=False)
        batch_op.create_index(batch_op.f('ix_identifications_score'), ['score'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identifications_score'))
        batch_op.drop_index('ix_identifications_chebi_score')
        batch_op.drop_index(batch_op.f('ix_identifications_chebi_id'))

    op.drop_table('identifications')
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studies_title'))

    op.drop_table('studies')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_instrument_manufacturer'))
        batch_op.drop_index(batch_op.f('ix_runs_acquisition_mode'))

    op.drop_table('runs')
    op.drop_table('provenance_records')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_uri'))
        batch_op.drop_index(batch_op.f('ix_files_file_sha256'))
        batch_op.drop_index(batch_op.f('ix_files_content_sha256'))

    op.drop_table('files')
    op.execute("DELETE FROM users WHERE id = 1")
    op.drop_table('users')
    # ### end Alembic commands ###
